### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by nickoe** [wayneandlayne/kicad-mac-builder#26]
```
17:21:50 [ 32%] Linking CXX shared library ../../../kicad/kicad.app/Contents/Frameworks/libkicad_3dsg.dylib
17:21:51 [ 35%] Built target gal
17:21:51 Undefined symbols for architecture x86_64:
17:21:51   "operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, wxScopedCharTypeBuffer<char> const&)", referenced from:
17:21:51       S3D::ReadCache(char const*, void*, bool (*)(char const*, void*)) in ifsg_api.cpp.o
17:21:51 ld: symbol(s) not found for architecture x86_64
17:21:51 clang: error: linker command failed with exit code 1 (use -v to see invocation)
17:21:51 make[5]: *** [kicad/kicad.app/Contents/Frameworks/libkicad_3dsg.2.0.0.dylib] Error 1
17:21:51 make[4]: *** [3d-viewer/3d_cache/sg/CMakeFiles/kicad_3dsg.dir/all] Error 2
17:21:51 make[4]: *** Waiting for unfinished jobs....
```

See complete log at http://ci.kicad-pcb.org/job/osx-kicad-adam-new-head/23/console

**Comment by adamwolf** [comment]
Hmm, my builds from last night worked on 10.11 through 10.13.   I'll take a
look!

**Comment by bstegmaier75** [comment]
This looks like an issue mixing libstdc++ and libc++. The switch happened around 10.8.
Are all libs built with the same minimum SDK version?

**Comment by bstegmaier75** [comment]
Usually, if you don't set anything the OS version is used. So, if you have macOS 10.11 it will use libc++ (e.g. for building wxWidgets).
If you now force KiCad build to something lower than 10.8 (when the switch happened), it will use a libstdc++ and that causes that kind of problems.

However, I am just guessing... I didn't have that problems for years now, because I never did build with such old min versions... but, it was a pain around the switched versions.

**Comment by adamwolf** [comment]
Ah, I bet that's it!

Set MACOS_MIN_VERSION please.

Does anyone know if there is a way to make CMake default to the current mac
os version, like I did in shell in build.sh?

`cmake -DMACOS_MIN_VERSION=`sw_vers -productVersion | cut -d. -f1-2``

**Comment by nickoe** [comment]
But at other times I see:
```
checking if C compiler (clang -mmacosx-version-min=10.11) works with SDK/version options... yes
checking if C++ compiler (clang++ -mmacosx-version-min=10.11) works with SDK/version options... yes
```
So that is probably a red herring.

**Comment by adamwolf** [comment]
Interesting.

**Comment by bstegmaier75** [comment]
I started to always specify clang and clang++ via environment variables (configure.sh) or on cmake command line.

If Xcode clang is the only compiler on the machine gcc and clang should be the same. But, I was never sure if it uses the same libraries if invoked as clang or gcc.

If you happen to have a real gcc on the system, I guess you will definitely run into trouble. At least back then when I tried gcc didn't use libc++.

**Comment by adamwolf** [comment]
I mean, if it's something we should always do, let's specify it in this
packaging suite.

Should we just set it in CMakeLists.txt?

**Comment by bstegmaier75** [comment]
I wouldn't do that.
It is no problem to use whatever compiler you want (in fact, for OpenMP you would have to specify some specific non-Xcode compiler to use).
You just have to make sure that all dependencies are built with something compatible.
In general this is no problem, the only thing that I know of is C++ stuff with libstdc++/libc++.

**Comment by nickoe** [comment]
OK, it seems to build not after I added ``-DMACOS_MIN_VERSION=`sw_vers -productVersion | cut -d. -f1-2` `` as fro the build.sh

**Comment by adamwolf** [comment]
I just set up https://github.com/wayneandlayne/kicad-mac-builder/pull/42 so hopefully we won't have this happen again.  Thanks for all the help, and sorry for all the back and forth!  Pretty soon I'll be able to remove the "does not work" from the repo description :)
